# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{thumbs}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Ciunelis"]
  s.date = %q{2011-01-23}
  s.description = %q{}
  s.email = %q{marcin.ciunelis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/thumbs.rb",
    "lib/thumbs/image.rb",
    "lib/thumbs/images/image_not_found.jpg",
    "lib/thumbs/middleware/cache_control.rb",
    "lib/thumbs/middleware/cache_read.rb",
    "lib/thumbs/middleware/cache_write.rb",
    "lib/thumbs/middleware/config.rb",
    "lib/thumbs/middleware/content_type.rb",
    "lib/thumbs/middleware/download.rb",
    "lib/thumbs/middleware/logger.rb",
    "lib/thumbs/middleware/not_found.rb",
    "lib/thumbs/middleware/resize.rb",
    "lib/thumbs/middleware/server_name.rb",
    "lib/thumbs/server.rb",
    "spec/spec_helper.rb",
    "spec/thumbs_spec.rb",
    "thumbs.gemspec"
  ]
  s.homepage = %q{http://github.com/martinciu/thumbs}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Image server proxy that can resize images on the fly. Built in ruby as a Rack application.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/thumbs_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rack-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<mini_magick>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rack-contrib>, [">= 0"])
      s.add_dependency(%q<mini_magick>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rack-contrib>, [">= 0"])
    s.add_dependency(%q<mini_magick>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

